rm(list=ls())

library(cowplot)
library(tidyr)
library(extrafont)
library(egg)
library(dplyr) 
#Note that an older version of dplyr (0.8.5) was used initially, 
#but we update it to dplyr (1.0.4) to use the nest_by function to accommodate broom updates
library(ggplot2)
library(broom)  

#sessionInfo() with package versions
#sf_0.9-6       scales_1.1.1   broom_0.7.0    egg_0.4.5      ggplot2_3.3.2  gridExtra_2.3  extrafont_0.17
#tidyr_1.1.2    cowplot_1.1.0  dplyr_1.0.4

#Results (output folder) will be generated by sourcing the corresponding scripts
load("data/Fig1_2.RData")
source("R/info.R")
source("R/Fig1_func.R")

source("R/Fig1.R")
source("R/Fig2.R")
source("R/Fig3.R")
source("R/Fig4.R")
source("R/OtherSIFigs.R")

